#-------------------------------
# General Site Settings
title: Connor
logo: # You can add own logo. For example '/images/logo.png'.
description: Dev log.
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://connorsabine.com"


#-------------------------------
# Author Settings
author:
  name: Connor Sabine
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Connor
  description: Dev log.
  image: '/images/01.jpg'

#-------------------------------
# Contact Settings
contact:
  email: connor@connorsabine.com # Add your email for contact form
  description: Contact Me. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/connor_sabine"}
- {icon: "ion-logo-github", link: "https://github.com/connorsabine"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/connorsabine"}


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

kramdown:
  parse_block_html: true

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
