#-------------------------------
# General Site Settings
title: Connor
logo: # You can add own logo. For example '/images/logo.png'.
description: Dev log.
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://connorsabine.com"


#-------------------------------
# Author Settings
author:
  name: Connor Sabine
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Connor
  description: Dev log.
  image: '/images/01.jpg'

#-------------------------------
# Contact Settings
contact:
  email: connor@connorsabine.com
  description: Contact Me.

#-------------------------------
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/connsabine"}
- {icon: "ion-logo-github", link: "https://github.com/connorsabine"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/connorsabine"}

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

kramdown:
  parse_block_html: true

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

collections:
  games:
    output: true

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
